#spring:
#  config:
#    activate:
#      on-profile: development
#  datasource:
#    url: jdbc:mysql://maz-tnbox-db-dev-mysql.mysql.database.azure.com:3306/cnc_ums_dev?useSSL=true
#    username: developer
#    password: tinteccnc3816
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#      javax:
#        persistence:
#          sharedcache:
#            mode: ENABLE_SELECTIVE
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update